catalogo/urls.py
# -*- coding: utf 8 -*-


from django.urls import path
from .views import lista_servicos, lista_por_categoria, detalhe_servico

app_name = 'catalogo'
urlpatterns = [
    path('', lista_servicos, name='lista_servicos'),
    path('<str:slug>/', lista_por_categoria, name='lista_por_categoria'),
    path('detalhe/<str:slug>/', detalhe_servico, name='detalhe_servico'),
]

orcamentos/urls.py
from django.urls import path
from .views import SolicitacaoView, OrcamentoView, SolicitacoesAbertasListView, OrcamentosListViewSolicitacoes
from .views import aceitarOrcamento, cancelarSolicitacao, descartarOrcamento, restaurarOrcamento, OrcamentosPrestador
from .views import cancelarOrcamento, confimarRealizacao
app_name = 'orcamentos'
urlpatterns = [
    path('solicitar/<str:slug>/', SolicitacaoView.as_view(), name='solicitar_orcamento'),
    path('novo/<int:pk>/', OrcamentoView.as_view(), name='novo_orcamento'),
    path('solicitacoes-abertas/', SolicitacoesAbertasListView.as_view(), name='solicitacoes_abertas'),
    path('orcamentos/solicitacoes/<int:pk>/', OrcamentosListViewSolicitacoes.as_view(), name='orcamentos_solicitacoes'),
    path('aceitar-orcamento/<int:orcamentopk>/<int:solicitacaopk>/', aceitarOrcamento, name='aceitar-orcamento'),
    path('cancelar-solicitacao/<int:solicitacaopk>/', cancelarSolicitacao, name='cancelar-solicitacao'),
    path('descartar-orcamento/<int:orcamentopk>/', descartarOrcamento, name='descartar-orcamento'),
    path('restaurar-orcamento/<int:orcamentopk>/', restaurarOrcamento, name='restaurar-orcamento'),
    path('orcamentos-dados/', OrcamentosPrestador.as_view(), name='orcamentos-dados'),
    path('cancelar-orcamento/<int:orcamentopk>/', cancelarOrcamento, name='cancelar-orcamento'),
    path('confirma-realizacao/<int:orcamentopk>/', confimarRealizacao, name='confirma-realizacao'),

]

perfis/urls.py
from django.urls import path
from .views import PerfilPrestador, PerfilCliente
app_name = 'perfis'
urlpatterns = [
    path('prestador/<int:pk>/', PerfilPrestador.as_view(), name='prefil_prestador'),
    path('cliente/<int:pk>/', PerfilCliente.as_view(), name='perfil_cliente'),
]

ruffus_core/urls.py
from django.contrib import admin
from django.urls import path, include
from catalogo.views import lista_servicos
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.conf import settings
from csite.views import home
urlpatterns = [
    path('', home, name='home'),
    path('index/', lista_servicos, name='index'),
    path('admin/', admin.site.urls),
    path('catalogo/', include('catalogo.urls', namespace='catalogo')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('orcamentos/', include('orcamentos.urls', namespace='orcamentos')),
    path('avaliacoes/', include('avaliacoes.urls', namespace='avaliacoes')),
    path('perfis/', include('perfis.urls', namespace='perfis')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from .views import ClienteCadastroView, logout_view, PrestadorCadastroView, PrestadorCategoriasView, Login, MinhaContaClienteView
from .views import AlterarSenhaView, EnderecoView, EnderecoListView, EnderecoEditar, EnderecoDeletar, DadosPessoaisList
from orcamentos.views import SolicitacaoListView


app_name = 'usuarios'
urlpatterns = [
    path('cadastro/cliente/', ClienteCadastroView.as_view(), name='cadastro_cliente'),
    path('cadastro/prestador/', PrestadorCadastroView.as_view(), name='cadastro_prestador'),
    path('cadastro/categorias/', PrestadorCategoriasView.as_view(), name='categorias_prestador'),
    path('cadastro/endereco/<str:redirecionamento>/', EnderecoView.as_view(), name='cadastro_endereco'),
    path('enderecos/', EnderecoListView.as_view(), name='lista_enderecos'),
    path('minha-conta/', MinhaContaClienteView.as_view(), name='cliente_conta'),
    path('alterar-senha/', AlterarSenhaView.as_view(), name='alterar_senha'),
    path('endereco/atualizar/<int:pk>/', EnderecoEditar.as_view(), name='editar_endereco'),
    path('endereco/deletar/<int:pk>/', EnderecoDeletar.as_view(), name='deletar_endereco'),
    path('dados-pessoais/', DadosPessoaisList.as_view(), name='dados_pessoais'),
    path('solicitacoes/', SolicitacaoListView.as_view(), name='solicitacoes_cliente'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Ruffus</title>
    {% block script %}
    {% endblock %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">

<link href="{% static 'bootstrap/css/nav-bar.css' %}" rel="stylesheet">
  <script type="text/javascript" src="{% static 'bootstrap/js/jquery-3.3.1.min.js' %}"></script>
</head>


    <body style="background-color: #ecf0f1;">
        <nav class="navbar navbar-expand-lg navbar-dark  " style="background-color: rgb(0,0,0) !important;">
            <a class="navbar-brand" ></a>
            <ul class="navbar-nav mr-auto">
                {% if not user.is_prestador %}
                <li class="nav-item active">
                    <a  class="nav-link" href="{% url 'index' %}">Início</a>
                </li>
                <li class="nav-item dropdown ml-auto">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-bars" aria-hidden="true"> Serviços</i></a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'catalogo:lista_servicos' %}">Listar todos</a>
                        {% for categoria in categorias %}
                            <a class="dropdown-item" href="{% url 'catalogo:lista_por_categoria' categoria.slug %}">{{ categoria }}</a>
                        {% endfor %}
                    </div>
                </li>
            {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios:cadastro_prestador' %}"><i class="fa fa-user" aria-hidden="true"></i> Seja um Prestador</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios:cadastro_cliente' %}"><i class="fa fa-user" aria-hidden="true"></i> Registrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios:login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Entrar</a>
                    </li>
                {% else %}
                        <li class="nav-item dropdown mr-auto">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fa fa-user" aria-hidden="true"> {{ user.username }}</i></a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'usuarios:cliente_conta' %}">Minha conta</a>
                                {% if user.is_cliente %}
                                    <a class="dropdown-item" href="{% url 'usuarios:solicitacoes_cliente' %}">Solicitações</a>
                                {% else %}
                                    <a class="dropdown-item" href="{% url 'orcamentos:solicitacoes_abertas' %}">Solicitações</a>
                                    <a class="dropdown-item" href="{% url 'orcamentos:orcamentos-dados' %}">Orçamentos dados</a>
                                    <a class="dropdown-item" href="{% url 'usuarios:categorias_prestador' %}">Categorias</a>
                                {% endif %}
                                <a class="dropdown-item" href="{% url 'usuarios:lista_enderecos' %}">Endereços</a>

                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'usuarios:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Sair</a>
                        </li>
                {% endif %}
            </ul>
        </nav>
        {% block messages %}
            {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissable" style="width: 100%; text-align: center;">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <strong>{{message}}</strong>
                </div>
            {% endfor %}
        {% endblock messages %}
        <div class="container">
            {% block container %}

            {% endblock %}
        </div>
              <!-- Placed at the end of the document so the pages load faster -->
        <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block container %}
    <div style="padding-bottom: 50px">
        <div class="jumbotron" style="background-color: whitesmoke; margin-top: 20px">
            <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center" style="margin-top: -60px">
              <h1 class="display-4">Bem vindo ao Ruffus</h1>
              <p class="lead">Somos uma plataforma de contratação de serviços que tem como objetivo fazer com que os usuários encontrem um trabalhador
                  para resolver o seu problema com um preço justo.
                  </p>
            </div>
        </div>
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal" style="text-align: center">Benefícios</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-12 mb-12 align-left">
                    <li> Maior facilidade em encontrar prestadores de serviços tornando esse processo mais ágil.</li>
                    <li> Possibilitar aos clientes escolherem os serviços mais baratos/confiáveis, tendo em vista que diversos prestadores podem dar seu orçamento para determinado serviço.</li>
                    <li> Aumentar a visibilidade dos prestadores, dando a possibilidade de aumento de renda.</li>
                    <li>Aumentar a segurança na contratação de serviços, tendo em vista que os prestadores passarão por um rigoroso critério de seleção.</li>
                    <li> Maior segurança no pagamento que é realizado pela plataforma.</li>
                </ul>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal" style="text-align: center">Como funciona?</h4>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="card-body">
                        <p class="card-text"><h2 style="text-align: center">Clientes</h2>
                        <p style="text-align: center">Você está precisando de um trabalhador para resolver um problema? é Preciso apenas fazer o cadastro, escolher a categoria
                            e fazer uma solicitação de orçamento. Prestadores de serviços darão orçamentos e você pode escolher aquele que cabe melhor no seu bolso</p>
                        <a href="{% url 'usuarios:cadastro_cliente' %}" class="btn btn-primary">Cadastro Cliente</a>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="card-body">
                        <p class="card-text"><h2 style="text-align: center">Prestadores</h2>
                        <p style="text-align: center">É preciso fazer o cadastro e aguardar o contato.
                            É importante sabe que verificamos antecedentes criminais e você não pode ter nenhum registro negativo.
                            Também solicitamos ao menos três testemunhas de que você já realizou serviços antes.
                        </p>
                            <a href="{% url 'usuarios:cadastro_prestador' %}" class="btn btn-primary" style="float: right;">Cadastro Prestador</a>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}