orcamentos/urls.py
from django.urls import path
from .views import SolicitacaoView, OrcamentoView, SolicitacoesAbertasListView, OrcamentosListViewSolicitacoes
from .views import aceitarOrcamento, cancelarSolicitacao, descartarOrcamento, restaurarOrcamento, OrcamentosPrestador
from .views import cancelarOrcamento, confimarRealizacao
app_name = 'orcamentos'
urlpatterns = [
    path('solicitar/<str:slug>/', SolicitacaoView.as_view(), name='solicitar_orcamento'),
    path('novo/<int:pk>/', OrcamentoView.as_view(), name='novo_orcamento'),
    path('solicitacoes-abertas/', SolicitacoesAbertasListView.as_view(), name='solicitacoes_abertas'),
    path('orcamentos/solicitacoes/<int:pk>/', OrcamentosListViewSolicitacoes.as_view(), name='orcamentos_solicitacoes'),
    path('aceitar-orcamento/<int:orcamentopk>/<int:solicitacaopk>/', aceitarOrcamento, name='aceitar-orcamento'),
    path('cancelar-solicitacao/<int:solicitacaopk>/', cancelarSolicitacao, name='cancelar-solicitacao'),
    path('descartar-orcamento/<int:orcamentopk>/', descartarOrcamento, name='descartar-orcamento'),
    path('restaurar-orcamento/<int:orcamentopk>/', restaurarOrcamento, name='restaurar-orcamento'),
    path('orcamentos-dados/', OrcamentosPrestador.as_view(), name='orcamentos-dados'),
    path('cancelar-orcamento/<int:orcamentopk>/', cancelarOrcamento, name='cancelar-orcamento'),
    path('confirma-realizacao/<int:orcamentopk>/', confimarRealizacao, name='confirma-realizacao'),

]

perfis/urls.py
from django.urls import path
from .views import PerfilPrestador, PerfilCliente
app_name = 'perfis'
urlpatterns = [
    path('prestador/<int:pk>/', PerfilPrestador.as_view(), name='prefil_prestador'),
    path('cliente/<int:pk>/', PerfilCliente.as_view(), name='perfil_cliente'),
]

ruffus_core/urls.py
from django.contrib import admin
from django.urls import path, include
from catalogo.views import lista_servicos
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.conf import settings
from csite.views import home
urlpatterns = [
    path('', home, name='home'),
    path('index/', lista_servicos, name='index'),
    path('admin/', admin.site.urls),
    path('catalogo/', include('catalogo.urls', namespace='catalogo')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('orcamentos/', include('orcamentos.urls', namespace='orcamentos')),
    path('avaliacoes/', include('avaliacoes.urls', namespace='avaliacoes')),
    path('perfis/', include('perfis.urls', namespace='perfis')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from .views import ClienteCadastroView, logout_view, PrestadorCadastroView, PrestadorCategoriasView, Login, MinhaContaClienteView
from .views import AlterarSenhaView, EnderecoView, EnderecoListView, EnderecoEditar, EnderecoDeletar, DadosPessoaisList
from orcamentos.views import SolicitacaoListView


app_name = 'usuarios'
urlpatterns = [
    path('cadastro/cliente/', ClienteCadastroView.as_view(), name='cadastro_cliente'),
    path('cadastro/prestador/', PrestadorCadastroView.as_view(), name='cadastro_prestador'),
    path('cadastro/categorias/', PrestadorCategoriasView.as_view(), name='categorias_prestador'),
    path('cadastro/endereco/<str:redirecionamento>/', EnderecoView.as_view(), name='cadastro_endereco'),
    path('enderecos/', EnderecoListView.as_view(), name='lista_enderecos'),
    path('minha-conta/', MinhaContaClienteView.as_view(), name='cliente_conta'),
    path('alterar-senha/', AlterarSenhaView.as_view(), name='alterar_senha'),
    path('endereco/atualizar/<int:pk>/', EnderecoEditar.as_view(), name='editar_endereco'),
    path('endereco/deletar/<int:pk>/', EnderecoDeletar.as_view(), name='deletar_endereco'),
    path('dados-pessoais/', DadosPessoaisList.as_view(), name='dados_pessoais'),
    path('solicitacoes/', SolicitacaoListView.as_view(), name='solicitacoes_cliente'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from catalogo.models import Categoria


class User(AbstractUser):

    is_cliente = models.BooleanField(default=False)
    is_prestador = models.BooleanField(default=False)


class Endereco(models.Model):

    nome_rua = models.CharField('Rua', max_length=50)
    complemento = models.CharField('Complemento', max_length=30, null=True, blank=True)
    bairro = models.CharField('Bairro', max_length=50)
    CEP = models.CharField('CEP', max_length=15)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.nome_rua + ' ' + self.complemento + ' ' + self.bairro


class Cliente(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    CPF = models.CharField('CPF', max_length=15)
    telefone = models.CharField('Telefone', max_length=15, blank=True, null=True)

    def __str__(self):
        return self.user.get_full_name()

    def get_status(self):
        status = {}
        if self.user.is_active:
            status = {
                'icone': 'fa fa-check-circle',
                'status': 'Perfil ativo',
                'color': 'green'
            }
        else:
            status = {
                'icone': 'fa fa-times-circle',
                'status': 'Perfil desativado',
                'color': 'red'
            }
        return status


class Prestador(models.Model):

    data_cadastro = models.DateField('Ingressou em', auto_now_add=True)
    telefone = models.CharField('Telefone', max_length=15)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    CPF = models.CharField('CPF', max_length=15, default='12345678')
    categorias = models.ManyToManyField(Categoria, blank=True)

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name_plural = 'Prestadores'
        verbose_name = 'Prestador'

    def get_categorias(self):
        categorias = Categoria.objects.filter(prestador=self)
        return categorias

    def get_status(self):
        status = {}
        if self.user.is_active:
            status = {
                'icone': 'fa fa-check-circle',
                'status': 'Perfil ativo',
                'color': 'green'
            }
        else:
            status = {
                'icone': 'fa fa-times-circle',
                'status': 'Perfil desativado',
                'color': 'red'
            }
        return status

usuarios/forms.py
from django.forms import ModelForm, CheckboxSelectMultiple
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from usuarios.models import Cliente, Endereco, User, Prestador


class ClienteCadastroForm(UserCreationForm):
    CPF = forms.CharField()
    telefone = forms.CharField()
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email', 'CPF')

    @transaction.atomic
    def save(self, cpf, telefone):
        user = super().save(commit=False)
        user.is_cliente = True
        user.save()
        Cliente.objects.create(user=user)
        user.cliente.CPF = cpf
        user.cliente.telefone = telefone
        user.cliente.save()
        return user


class PrestadorCadastroForm(UserCreationForm):
    CPF = forms.CharField()
    telefone = forms.CharField()
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email', 'CPF')

    @transaction.atomic
    def save(self, cpf, telefone):
        user = super().save(commit=False)

        user.is_prestador = True
        user.is_active = True
        user.save()
        Prestador.objects.create(user=user)
        user.prestador.CPF = cpf
        user.prestador.telefone = telefone
        user.prestador.save()

        return user


class PrestadorCategoriasForm(ModelForm):
    class Meta:
        model = Prestador
        fields = ('categorias', )
        widgets = {
            'categorias': CheckboxSelectMultiple
        }


class EnderecoForm(ModelForm):

    class Meta:

        model = Endereco
        fields = ['nome_rua', 'complemento', 'bairro', 'CEP', ]

usuarios/views.py
from django.contrib.auth import login, REDIRECT_FIELD_NAME
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import CreateView, UpdateView, TemplateView, FormView, ListView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .decorators import cliente_required, prestador_required
from .forms import ClienteCadastroForm, PrestadorCadastroForm, EnderecoForm, PrestadorCategoriasForm
from .models import User, Endereco, Prestador, Cliente
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView

''' VIEW CLIENTES '''


class ClienteCadastroView(CreateView):
    model = User
    form_class = ClienteCadastroForm
    template_name = 'usuarios/cadastro_cliente_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'cliente'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        cpf = form.cleaned_data['CPF']
        telefone = form.cleaned_data['telefone']
        user = form.save(cpf, telefone)
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Usuario cadastrado com sucesso!')
        return reverse('index')


'''VIEW PRESTADORES'''


class PrestadorCadastroView(CreateView):

    model = User
    form_class = PrestadorCadastroForm
    template_name = 'usuarios/cadastro_prestador_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'prestador'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        cpf = form.cleaned_data['CPF']
        telefone = form.cleaned_data['telefone']
        user = form.save(cpf, telefone)
        #login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        messages.warning(self.request, 'Cadastro realizado com sucesso! Usuário aguardando análise')
        return reverse('index')


@method_decorator([login_required(login_url='usuarios:login'), prestador_required(login_url='usuarios:login')], name='dispatch')
class PrestadorCategoriasView(UpdateView):

    model = Prestador
    form_class = PrestadorCategoriasForm
    template_name = 'usuarios/prestador_categorias_form.html'
    success_url = reverse_lazy('usuarios:cliente_conta')

    def get_object(self):
        return self.request.user.prestador

    def form_valid(self, form):
        messages.success(self.request, 'Categorias atualizadas com sucesso!')
        return super().form_valid(form)


'''VIEWS COMUM DOS DOIS'''

@login_required()
def logout_view(request):
    logout(request)
    messages.success(request, 'Desconectado com sucesso!')
    return redirect('index')


class Login(LoginView):
    form_class = AuthenticationForm
    authentication_form = None
    template_name = 'usuarios/login.html'
    redirect_authenticated_user = 'index'

    def get_success_url(self):
        #messages.success(self.request, 'Usuário logado')
        if self.request.user.is_prestador:
            return reverse('usuarios:cliente_conta')
        else:
            return reverse('index')


@method_decorator([login_required(login_url='usuarios:login')], name='dispatch')
class MinhaContaClienteView(TemplateView):
    template_name = 'usuarios/minha_conta_cliente.html'


@method_decorator([login_required(login_url='usuarios:login')], name='dispatch')
class AlterarSenhaView(FormView):

    template_name = 'usuarios/alterar_senha.html'
    #success_url = reverse_lazy('usuarios:cliente_conta')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(AlterarSenhaView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Senha alterada com sucesso!')
        return reverse('usuarios:cliente_conta')


@method_decorator([login_required(login_url='usuarios:login')], name='dispatch')
class EnderecoView(CreateView):

    model = Endereco
    form_class = EnderecoForm
    template_name = 'usuarios/cadastro_endereco.html'

    def form_valid(self, form):
        form.instance.usuario = self.request.user
        form.save()
        return self.get_success_url()

    def get_success_url(self):
        messages.success(self.request, 'Endereco cadastrado com sucesso')
        redirecionamento = self.kwargs['redirecionamento']
        if redirecionamento == 'None':
            return redirect('usuarios:lista_enderecos')
        else:
            return redirect('orcamentos:solicitar_orcamento', redirecionamento)

@method_decorator([login_required(login_url='usuarios:login')], name='dispatch')
class EnderecoListView(ListView):

    template_name = 'usuarios/lista_endereco.html'
    context_object_name = 'enderecos'

    #paginate_by = 5

    def get_queryset(self):
        return Endereco.objects.filter(usuario=self.request.user)


@method_decorator([login_required(login_url='usuarios:login')], name='dispatch')
class EnderecoEditar(UpdateView):

    model = Endereco
    form_class = EnderecoForm
    template_name = 'usuarios/cadastro_endereco.html'
    success_url = reverse_lazy('usuarios:lista_enderecos')

    def get_object(self):
        return get_object_or_404(Endereco, pk=self.kwargs['pk'], usuario=self.request.user)

    def form_valid(self, form):
        form.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Endereco atualizado com sucesso')
        return reverse('usuarios:lista_enderecos')


@method_decorator([login_required(login_url='usuarios:login')], name='dispatch')
class EnderecoDeletar(DeleteView):

    template_name_suffix = '_confirma_exclusao'
    model = Endereco

    def get_object(self):
        return get_object_or_404(Endereco, pk=self.kwargs['pk'], usuario=self.request.user)

    def get_success_url(self):
        messages.success(self.request, 'Endereco removido com sucesso')
        return reverse('usuarios:lista_enderecos')


@method_decorator([login_required(login_url='usuarios:login')], name='dispatch')
class DadosPessoaisList(ListView):
    template_name = 'usuarios/dados_pessoais.html'
    context_object_name = 'dados'

    #paginate_by = 5

    def get_queryset(self):
        if self.request.user.is_prestador:
            return Prestador.objects.get(user=self.request.user)
        return Cliente.objects.get(user=self.request.user)

usuarios/templates/usuarios/alterar_senha.html
{% extends 'usuarios/minha_conta_cliente.html' %}
{% load widget_tweaks %}

{% block conta %}


    <h3 class="pull-right mb-4">Alterar senha</h3>
    <form class="form-horizontal" method='post' style="padding-top: 30px">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
                <div class="form-group {% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.auto_id }}" class="col-sm-6 sr-only"> {{field.label }}</label>
                    <div class="">
                        {% render_field field class="form-control" placeholder=field.label  %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <span class="help-block"> {{ error }}</span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <button style="float: right" class="btn btn-success align-right" type="submit">Alterar</button>
        </fieldset>
    </form>

{% endblock %}

usuarios/templates/usuarios/atualizar_endereco.html
{% extends 'usuarios/minha_conta_cliente.html' %}
{% load widget_tweaks %}

{% block conta %}


    <h3 class="pull-right mb-4">Atualizar endereço</h3>
    <form class="form-horizontal" method='post' style="padding-top: 80px">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
                <div class="form-group {% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.auto_id }}" class="col-sm-6 sr-only"> {{field.label }}</label>
                    <div class="">
                        {% render_field field class="form-control" placeholder=field.label  %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <span class="help-block"> {{ error }}</span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <button class="btn btn-success align-right" type="submit">Alterar</button>
        </fieldset>
    </form>

{% endblock %}

usuarios/templates/usuarios/cadastro_cliente_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{%  load static %}

{% block script %}
      <link href="{% static 'bootstrap/css/registro_cliente.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
  {% endblock %}

{% block container %}

    <div  style="margin-top: 15px;">
        <article class="card-body mx-auto" style="max-width: 400px;">
	        <h4 class="card-title mt-3 text-center">Crie uma conta</h4>
	        <p class="text-center">Comece com sua conta gratuita</p>

	        <form method="post">
                {% csrf_token %}
                 <div class="form-group input-group">
                     {{ form.username.errors }}
		            <div class="input-group-prepend">
		                <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		            </div>
                    {% render_field form.username class="form-control" placeholder='Nome de usuário' %}
                </div> <!-- form-group// -->
	            <div class="form-group input-group">
                    <p class="help-block"><small>{{ form.first_name.errors }}</small></p>
                    {{ form.first_name.errors }}
		            <div class="input-group-prepend">
		                <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		            </div>
                    {% render_field form.first_name class="form-control" placeholder='Nome' %}
                </div> <!-- form-group// -->
                <div class="form-group input-group">
                     {{ form.last_name.errors }}
		            <div class="input-group-prepend">
		                <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		            </div>
                    {% render_field form.last_name class="form-control" placeholder='Sobrenome' %}
                </div> <!-- form-group// -->
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                         {{ form.email.errors }}
                        <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                     </div>
                     {% render_field form.email class="form-control" placeholder='Email' %}
                </div> <!-- form-group// -->
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                         {{ form.CPF.errors }}
                        <span class="input-group-text"> <i class="fas fa-id-card"></i> </span>
                     </div>
                     {% render_field form.CPF class="form-control" placeholder='CPF' %}
                </div> <!-- form-group// -->
                    <div class="form-group input-group">
                    <div class="input-group-prepend">
                         {{ form.telefone.errors }}
                        <span class="input-group-text"> <i class="fas fa-mobile-alt"></i> </span>
                     </div>
                     {% render_field form.telefone class="form-control" placeholder='Telefone' %}
                </div> <!-- form-group// -->
                <div class="form-group input-group">
                     {{ form.password1.errors }}
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    {% render_field form.password1 class="form-control" placeholder='Senha' %}
                </div> <!-- form-group// -->
                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    {% render_field form.password2 class="form-control" placeholder='Confirmação de senha' %}
                </div> <!-- form-group// -->
                 {% if form.password2.errors %}
                    <div class="alert alert-warning">
                        {{ form.password2.errors }}
                    </div>
                    {% endif %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block"> Criar Conta  </button>
                </div> <!-- form-group// -->
                <p class="text-center">Já possui uma conta? <a href="{% url 'usuarios:login' %}">Entrar</a> </p>
            </form>
        </article>
    </div> <!-- card.// -->

    <!--
    <h2>Cadastro novo usuário</h2>
    <form method='post'>
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
                <div class="form-group {% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.auto_id }}" class="col-sm-6 sr-only"> {{field.label }}</label>
                    <div class="">
                        {% render_field field class="form-control form-control-sm" placeholder=field.label  %}
                        {% for error in field.errors %}
                            <span class="help-block"> {{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <button class="btn btn-primary " type="submit">Cadastrar</button>
        </fieldset>
    </form>
-->
{% endblock %}

usuarios/templates/usuarios/cadastro_endereco.html
{% extends 'usuarios/minha_conta_cliente.html' %}
{% load widget_tweaks %}

{% block conta %}

    <h3 class="pull-right mb-4">Endereço</h3>
    <form class="form-horizontal" method='post' style="padding-top: 80px">
        {% csrf_token %}
        <fieldset>
   {% for field in form %}
                <div class="form-group {% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.auto_id }}" class="col-sm-6 sr-only"> {{field.label }}</label>
                    <div class="">
                        {% render_field field class="form-control" placeholder=field.label  %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <span class="help-block"> {{ error }}</span>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}

       </fieldset>

            <button style="float: right" class="btn btn-success align-right" type="submit">Salvar</button>
            <a style="float: right; margin-right: 5px !important;" href="{% url 'usuarios:lista_enderecos' %}"><button type="button" class="btn btn-secondary">Cancelar</button></a>

        </fieldset>
    </form>


{% endblock %}

usuarios/templates/usuarios/lista_endereco.html
{% extends 'usuarios/minha_conta_cliente.html' %}
{% load widget_tweaks %}

{% block conta %}
    <div style="padding-bottom: 80px">
        <h3 class="pull-right mb-4">Endereços</h3>
    </div>
    <div style="margin-top: -80px !important;">
    {% if not enderecos %}
        <span id="notifications" class="">
            Você não possui endereços cadastrados
        </span>
    {% else %}
    {% for endereco in enderecos %}
        <div class="my-3 p-3 bg-white rounded box-shadow" style="margin-left: -50px; ">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                <strong class="text-gray-dark">
                    {{ endereco.nome_rua }}
                </strong>
            </p>
            <div class="media pt-3">
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <strong class="text-gray-dark">Rua: </strong>{{ endereco.nome_rua }}
                    <strong class=""><br>Complemento: </strong>{{ endereco.complemento  }}
                    <strong class=""><br>Bairro: </strong>{{ endereco.bairro }}
                    <strong class=""><br>CEP: </strong>{{ endereco.CEP }}
                </p>
            </div>
            <div class="media" >
                <a href="{% url 'usuarios:editar_endereco' endereco.pk %}"> <button type="button" class="btn btn-sm btn-outline-warning" style="float: right !important; margin-right: 10px">Editar</button></a>
                <a href="{% url 'usuarios:deletar_endereco' endereco.pk %}"><button type="button" class="btn btn-sm btn-outline-danger" style="float: right !important; margin-right: 10px">Excluir</button></a>
            </div>
        </div>
    {% endfor %}
    {% endif %}
        <div style="padding-top: 50px; padding-bottom: 100px">
            <a href="{% url 'usuarios:cadastro_endereco' None %}"><button class="btn btn-info">Cadastrar novo endereço</button></a>
        </div>
    </div>
{% endblock %}

usuarios/templates/usuarios/login.html
{% extends "base.html" %}
{% load widget_tweaks %}
{%  load static %}

{% block script %}
      <link href="{% static 'bootstrap/css/registro_cliente.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
  {% endblock %}

{% block container %}

    <div  style="margin-top: 15px;">
        <article class="card-body mx-auto" style="max-width: 400px;">
	        <h4 class="card-title mt-3 text-center">Login</h4>
	        <p class="text-center">Conecte-se para começar a usar</p>
	        <form method="post">
                {% csrf_token %}
                 <div class="form-group input-group">
                     {{ form.username.errors }}
		            <div class="input-group-prepend">
		                <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		            </div>
                    {% render_field form.username class="form-control" placeholder='Username' %}


                    </div> <!-- form-group// -->

                <div class="form-group input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    {% render_field form.password class="form-control" placeholder='Senha' %}
                </div> <!-- form-group// -->


                 {% for error in form.non_field_errors %}
                     <div class="alert alert-warning">
                            {{ error }}
                        </div>
                 {% endfor %}

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Entrar </button>
                </div> <!-- form-group// -->
                <p class="text-center">Não possui conta? <a href="{% url 'usuarios:cadastro_cliente' %}">Cadastrar</a> </p>
            </form>
        </article>
    </div> <!-- card.// -->
{% endblock %}

usuarios/templates/usuarios/minha_conta_cliente.html
{% extends "base.html" %}
{% load widget_tweaks %}
{%  load static %}


{% block script %}
    	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  {% endblock %}

{% block container %}

	<div class="row bg-dark mb-4 my-4 text-white">
		<h2>Minha Conta</h2>
	</div>

	<div class="row">
	    <!-- side nav-->
	    <aside class="col-sm-6 col-md-3 card  my-4">
	        <h3>{{ user.get_full_name }}</h3>
	        <hr/>
	        <ul style="list-style: none">
	            <li>
	                <a href="{% url 'usuarios:dados_pessoais' %}" class="active">
    	                <span class="fa fa-user"></span>
    	                Dados pessoais
	                </a>
	            </li>
	            <li>
	                <a href="{% url 'usuarios:alterar_senha' %}">
    	                <span class="fa fa-lock"></span>
    	                Trocar senha
	                </a>
	            </li>
	            <li>
	                <a href="{% url 'usuarios:lista_enderecos' %}">
    	                <span class="fa fa-address-card"></span>
    	                Meus endereços
	                </a>
	            </li>
            {% if user.is_cliente %}
	            <li>
	                <a href="{% url 'usuarios:solicitacoes_cliente' %}">
    	                <span class="fa fa-money"></span>
    	                Minhas solicitações
	                </a>
	            </li>
            {% endif %}
	            {% if user.is_prestador %}
                <li>
	                <a href="{% url 'usuarios:categorias_prestador' %}">
	                    <span class="fa fa-briefcase "></span>
	                    Categorias
	                </a>
	            </li>
                    <li>
	                <a href="{% url 'orcamentos:solicitacoes_abertas' %}">
	                    <span class="fa fa-briefcase "></span>
	                    Solicitações de orçamento
	                </a>
	            </li>
                    </li>
                    <li>
	                <a href="{% url 'orcamentos:orcamentos-dados' %}">
	                    <span class="fa fa-briefcase "></span>
	                    Orçamentos dados
	                </a>
	            </li>
                {% endif %}
	        </ul>
	    </aside>

	    <section class="col-sm-6 col-md-8 offset-md-1" id="main-content">
	        {% block conta %}

            <h3 class="pull-right mb-4">Configurações gerais</h3>
	            <div class="row" style="padding-top: 80px">
	                <label for="notifications"></label>
                    <span id="notifications" class="">
                        Essa é a página de gerência dos seus dados.
                        Você pode escolher o que deseja fazer pelo menu lateral.
                        <br/>
                        Você pode cadastrar e alterar seu endereços, acompanhar pagamentos e pedidos de orçamento
                    </span>
                </div>

            {% endblock conta %}

	    </section>

	</div>
{% endblock %}