catalogo/urls.py
# -*- coding: utf 8 -*-


from django.urls import path
from .views import lista_servicos, lista_por_categoria, detalhe_servico

app_name = 'catalogo'
urlpatterns = [
    path('', lista_servicos, name='lista_servicos'),
    path('<str:slug>/', lista_por_categoria, name='lista_por_categoria'),
    path('detalhe/<str:slug>/', detalhe_servico, name='detalhe_servico'),
]

orcamentos/urls.py
from django.urls import path
from .views import SolicitacaoView, OrcamentoView, SolicitacoesAbertasListView, OrcamentosListViewSolicitacoes
from .views import aceitarOrcamento, cancelarSolicitacao, descartarOrcamento, restaurarOrcamento, OrcamentosPrestador
from .views import cancelarOrcamento, confimarRealizacao
app_name = 'orcamentos'
urlpatterns = [
    path('solicitar/<str:slug>/', SolicitacaoView.as_view(), name='solicitar_orcamento'),
    path('novo/<int:pk>/', OrcamentoView.as_view(), name='novo_orcamento'),
    path('solicitacoes-abertas/', SolicitacoesAbertasListView.as_view(), name='solicitacoes_abertas'),
    path('orcamentos/solicitacoes/<int:pk>/', OrcamentosListViewSolicitacoes.as_view(), name='orcamentos_solicitacoes'),
    path('aceitar-orcamento/<int:orcamentopk>/<int:solicitacaopk>/', aceitarOrcamento, name='aceitar-orcamento'),
    path('cancelar-solicitacao/<int:solicitacaopk>/', cancelarSolicitacao, name='cancelar-solicitacao'),
    path('descartar-orcamento/<int:orcamentopk>/', descartarOrcamento, name='descartar-orcamento'),
    path('restaurar-orcamento/<int:orcamentopk>/', restaurarOrcamento, name='restaurar-orcamento'),
    path('orcamentos-dados/', OrcamentosPrestador.as_view(), name='orcamentos-dados'),
    path('cancelar-orcamento/<int:orcamentopk>/', cancelarOrcamento, name='cancelar-orcamento'),
    path('confirma-realizacao/<int:orcamentopk>/', confimarRealizacao, name='confirma-realizacao'),

]

perfis/urls.py
from django.urls import path
from .views import PerfilPrestador, PerfilCliente
app_name = 'perfis'
urlpatterns = [
    path('prestador/<int:pk>/', PerfilPrestador.as_view(), name='prefil_prestador'),
    path('cliente/<int:pk>/', PerfilCliente.as_view(), name='perfil_cliente'),
]

ruffus_core/urls.py
from django.contrib import admin
from django.urls import path, include
from catalogo.views import lista_servicos
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.conf import settings
from csite.views import home
urlpatterns = [
    path('', home, name='home'),
    path('index/', lista_servicos, name='index'),
    path('admin/', admin.site.urls),
    path('catalogo/', include('catalogo.urls', namespace='catalogo')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('orcamentos/', include('orcamentos.urls', namespace='orcamentos')),
    path('avaliacoes/', include('avaliacoes.urls', namespace='avaliacoes')),
    path('perfis/', include('perfis.urls', namespace='perfis')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/models.py
# -*- coding: utf 8 -*-


from django.db import models
from django.urls import reverse


# Create your models here.
class Categoria(models.Model):

    nome = models.CharField('Nome', max_length=50)
    slug = models.CharField('Identificador', max_length=50)
    data_criacao = models.DateTimeField('Criado em', auto_now_add=True)
    data_modificacao = models.DateTimeField('Modificado em', auto_now=True)
    imagem = models.ImageField('Imagem', upload_to='categorias', blank=True, null=True)

    class Meta:

        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['nome']

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('catalogo:lista_por_categoria', kwargs={'slug': self.slug})


class Servico(models.Model):

    nome = models.CharField('Nome', max_length=50)
    slug = models.CharField('Identificador', max_length=50)
    categoria = models.ForeignKey(Categoria, verbose_name='Categoria', on_delete=models.PROTECT)
    descricao = models.TextField('Descrição', blank=True)
    data_criacao = models.DateTimeField('Criado em', auto_now_add=True)
    data_modificacao = models.DateTimeField('Modificado em', auto_now=True)
    preco = models.DecimalField('Preço', decimal_places=2, max_digits=10)
    imagem = models.ImageField('Imagem', upload_to='servicos', blank=True, null=True)

    class Meta:

        verbose_name = 'Serviço'
        verbose_name_plural = 'Serviços'
        ordering = ['nome']

    def __str__(self):
        return self.nome

catalogo/views.py
# -*- coding: utf 8 -*-

from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views import generic
from .models import Servico, Categoria
from usuarios.decorators import cliente_required


class ListaServicosView(generic.ListView):

    model = Servico
    template_name = 'catalogo/lista_servicos.html'
    context_object_name = 'servicos'


lista_servicos = ListaServicosView.as_view()


class ListaPorCategoriaView(generic.ListView):

    template_name = 'catalogo/servicos_categoria.html'
    context_object_name = 'servicos'

    def get_queryset(self):

        categoria = get_object_or_404(Categoria, slug=self.kwargs['slug'])
        return Servico.objects.filter(categoria=categoria)

    def get_context_data(self, **kwargs):
        context = super(ListaPorCategoriaView, self).get_context_data(**kwargs)
        context['categoria_atual'] = get_object_or_404(Categoria, slug=self.kwargs['slug'])
        return context


lista_por_categoria = ListaPorCategoriaView.as_view()


@method_decorator([cliente_required(login_url='usuarios:login')], name='dispatch')
class DetalheServicoView(generic.ListView):

    template_name = 'catalogo/detalhe_servico.html'
    context_object_name = 'servico'

    def get_queryset(self):
        return Servico.objects.get(slug=self.kwargs['slug'])


detalhe_servico = DetalheServicoView.as_view()

catalogo/templates/catalogo/detalhe_servico.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
<style>

.landing {
  margin-top: 50px;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-pack: center;
      -ms-flex-pack: center;
          justify-content: center;
  -webkit-box-align: center;
      -ms-flex-align: center;
          align-items: center;
}



.page {
  border-radius: 8px;
  box-shadow: 0 9px 50px 4px rgba(0, 0, 0, 0.4);
  background: white;
  width: 80%;
  height: 80%;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: horizontal;
  -webkit-box-direction: normal;
      -ms-flex-direction: row;
          flex-direction: row;
  overflow: hidden;
}
.page .image {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-pack: center;
      -ms-flex-pack: center;
          justify-content: center;
  -webkit-box-align: center;
      -ms-flex-align: center;
          align-items: center;
  height: 100%;
  width: 50%;
}
.page .image img {
    margin-top: 100px !important;
  width: 90%;
}
.page .about {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
      -ms-flex-direction: column;
          flex-direction: column;
  padding: 25px;
  max-width: 50%;
  -webkit-box-pack: justify;
      -ms-flex-pack: justify;
          justify-content: space-between;
}
.page .about .main {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
      -ms-flex-direction: column;
          flex-direction: column;
}
.page .about .main .title {
  color: rgba(0, 0, 0, 0.8);
  font-size: 28px;
  padding: 16px 0 32px 0;
  font-weight: 400;
}
.page .about .main .description p {
  color: rgba(0, 0, 0, 0.7);
  font-size: 18px;
  line-height: 20px;
  font-weight: 400;
  padding-bottom: 16px;
}
.page .about .controls {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-pack: end;
      -ms-flex-pack: end;
          justify-content: flex-end;
}
.page .about .controls .try {
  cursor: pointer;
  border-radius: 8px;
  padding: 8px;
  color: #f4f5f7;
  background: #3f51b5;
}

@media only screen and (min-width: 1024px) {
  .page {
    max-width: 900px;
    max-height: 700px;

  }
}
@media only screen and (max-width: 480px) {
  .landing {
    background: #ecf0f1;
  }



  .page {
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
        -ms-flex-direction: column;
            flex-direction: column;
  }
  .page .image {

    padding-top: 8px;
    width: 100%;
    height: 20%;
  }
  .page .image img {

    height: 100%;
    width: initial;
  }
  .page .about {

    overflow-y: scroll;
    max-width: 100%;
  }
}
</style>
{% endblock %}
{% block container %}
<div class="landing">
    <div class="page">
        <div class="image">
            <img src="{{ servico.imagem.url }}" />
        </div>
        <div class="about">
            <div class="main">
                <div class="title">
                    {{ servico }}
                </div>
                <div class="description">
                    {{ servico.descricao }}
                </div>
                <div>
                    {% block solicitacao %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock container %}

catalogo/templates/catalogo/lista_servicos.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
<link href="{% static 'bootstrap/css/cards.css' %}" rel="stylesheet">
{% endblock %}
{% block container %}
<section class="details-card">
    <div class="container">
        <div class="row">
            {% for servico in servicos %}
                <div class="col-md-4">
                    <div class="card-content">
                        <div class="card-img">
                             <a href="{% url 'orcamentos:solicitar_orcamento' servico.slug %}">
                            {% if servico.imagem %}
                                <img src="{{ servico.imagem.url }}" alt="">
                            {% else %}
                                <img src="https://placeimg.com/380/230/any" alt="">
                            {% endif %}
                             </a>
                            <!--<span><h4>heading</h4></span> -->
                        </div>
                        <div class="card-desc">
                            <h3>{{ servico.nome }}</h3>
                            <p>{{ servico.descricao }}</p>
                                <a href="{% url 'orcamentos:solicitar_orcamento' servico.slug %}" class="btn-card">Solicitar orçamento</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

catalogo/templates/catalogo/servicos_categoria.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
<link href="{% static 'bootstrap/css/cards.css' %}" rel="stylesheet">
    <style>
        .my-header{
            text-align: center;
        }
    section{
        padding: 45px 0 !important;
}
    </style>
{% endblock %}
{% block container %}
<section class="details-card">
    <h1 class="my-header"> Serviços {{ categoria_atual }}</h1>
    <div class="container">

        <div class="row">
            {% for servico in servicos %}
                <div class="col-md-4">
                    <div class="card-content">
                        <div class="card-img">
                            <a href="{% url 'orcamentos:solicitar_orcamento' servico.slug %}">
                              {% if servico.imagem %}
                                <img src="{{ servico.imagem.url }}" alt="">
                            {% else %}
                                <img src="https://placeimg.com/380/230/any" alt="">
                            {% endif %}
                             </a>
                            <!--<span><h4>heading</h4></span> -->
                        </div>
                        <div class="card-desc">
                            <h3>{{ servico.nome }}</h3>
                            <p>{{ servico.descricao }}</p>
                                <a href="{% url 'orcamentos:solicitar_orcamento' servico.slug %}" class="btn-card">Solicitar orçamento</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}