avaliacoes/urls.py
from django.urls import path
from .views import AvaliacaoView, AvaliacaoPeloPrestador

app_name = 'avaliacoes'
urlpatterns = [
    path('avaliar/<str:orcamentopk>/', AvaliacaoView.as_view(), name='avaliar'),
    path('avaliar-usuario/<int:orcamentopk>/', AvaliacaoPeloPrestador.as_view(), name='avaliar_cliente'),
]

orcamentos/urls.py
from django.urls import path
from .views import SolicitacaoView, OrcamentoView, SolicitacoesAbertasListView, OrcamentosListViewSolicitacoes
from .views import aceitarOrcamento, cancelarSolicitacao, descartarOrcamento, restaurarOrcamento, OrcamentosPrestador
from .views import cancelarOrcamento, confimarRealizacao
app_name = 'orcamentos'
urlpatterns = [
    path('solicitar/<str:slug>/', SolicitacaoView.as_view(), name='solicitar_orcamento'),
    path('novo/<int:pk>/', OrcamentoView.as_view(), name='novo_orcamento'),
    path('solicitacoes-abertas/', SolicitacoesAbertasListView.as_view(), name='solicitacoes_abertas'),
    path('orcamentos/solicitacoes/<int:pk>/', OrcamentosListViewSolicitacoes.as_view(), name='orcamentos_solicitacoes'),
    path('aceitar-orcamento/<int:orcamentopk>/<int:solicitacaopk>/', aceitarOrcamento, name='aceitar-orcamento'),
    path('cancelar-solicitacao/<int:solicitacaopk>/', cancelarSolicitacao, name='cancelar-solicitacao'),
    path('descartar-orcamento/<int:orcamentopk>/', descartarOrcamento, name='descartar-orcamento'),
    path('restaurar-orcamento/<int:orcamentopk>/', restaurarOrcamento, name='restaurar-orcamento'),
    path('orcamentos-dados/', OrcamentosPrestador.as_view(), name='orcamentos-dados'),
    path('cancelar-orcamento/<int:orcamentopk>/', cancelarOrcamento, name='cancelar-orcamento'),
    path('confirma-realizacao/<int:orcamentopk>/', confimarRealizacao, name='confirma-realizacao'),

]

perfis/urls.py
from django.urls import path
from .views import PerfilPrestador, PerfilCliente
app_name = 'perfis'
urlpatterns = [
    path('prestador/<int:pk>/', PerfilPrestador.as_view(), name='prefil_prestador'),
    path('cliente/<int:pk>/', PerfilCliente.as_view(), name='perfil_cliente'),
]

ruffus_core/urls.py
from django.contrib import admin
from django.urls import path, include
from catalogo.views import lista_servicos
from django.views.static import serve as serve_static
from django.conf.urls.static import static
from django.conf import settings
from csite.views import home
urlpatterns = [
    path('', home, name='home'),
    path('index/', lista_servicos, name='index'),
    path('admin/', admin.site.urls),
    path('catalogo/', include('catalogo.urls', namespace='catalogo')),
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('orcamentos/', include('orcamentos.urls', namespace='orcamentos')),
    path('avaliacoes/', include('avaliacoes.urls', namespace='avaliacoes')),
    path('perfis/', include('perfis.urls', namespace='perfis')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from .views import ClienteCadastroView, logout_view, PrestadorCadastroView, PrestadorCategoriasView, Login, MinhaContaClienteView
from .views import AlterarSenhaView, EnderecoView, EnderecoListView, EnderecoEditar, EnderecoDeletar, DadosPessoaisList
from orcamentos.views import SolicitacaoListView


app_name = 'usuarios'
urlpatterns = [
    path('cadastro/cliente/', ClienteCadastroView.as_view(), name='cadastro_cliente'),
    path('cadastro/prestador/', PrestadorCadastroView.as_view(), name='cadastro_prestador'),
    path('cadastro/categorias/', PrestadorCategoriasView.as_view(), name='categorias_prestador'),
    path('cadastro/endereco/<str:redirecionamento>/', EnderecoView.as_view(), name='cadastro_endereco'),
    path('enderecos/', EnderecoListView.as_view(), name='lista_enderecos'),
    path('minha-conta/', MinhaContaClienteView.as_view(), name='cliente_conta'),
    path('alterar-senha/', AlterarSenhaView.as_view(), name='alterar_senha'),
    path('endereco/atualizar/<int:pk>/', EnderecoEditar.as_view(), name='editar_endereco'),
    path('endereco/deletar/<int:pk>/', EnderecoDeletar.as_view(), name='deletar_endereco'),
    path('dados-pessoais/', DadosPessoaisList.as_view(), name='dados_pessoais'),
    path('solicitacoes/', SolicitacaoListView.as_view(), name='solicitacoes_cliente'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

orcamentos/models.py
from django.db import models
from usuarios.models import Cliente, Endereco, Prestador
from catalogo.models import Servico
# Create your models here.


class Solicitacao(models.Model):

    SOLICITACAO_STATUS = (
        (0, 'Solicitado'),
        (1, 'Aguardando prestador'),
        (2, 'Cancelado pelo cliente'),
        (3, 'Cancelado pelo prestador'),
        (4, 'Aguardando pagamento'),
        (5, 'Concluido')
    )

    cliente = models.ForeignKey('usuarios.Cliente', related_name='Cliente', on_delete=models.CASCADE)
    servico = models.ForeignKey('catalogo.Servico', on_delete=models.CASCADE)
    status = models.IntegerField('Status', choices=SOLICITACAO_STATUS, default=0)
    endereco = models.ForeignKey('usuarios.Endereco', default='', verbose_name='Endereço', on_delete=models.CASCADE, null=False, blank=False)
    descricao = models.TextField('Descricao')
    hora_solicitacao = models.DateTimeField(auto_now_add=True)
    hora_aceitacao = models.DateTimeField(auto_now=True)
    orcamento_aceito = models.OneToOneField('orcamentos.Orcamento',related_name='orcamento_aceito', on_delete=models.CASCADE, null=True, blank=True)
    avaliado = models.BooleanField(default=False)
    prestador_avaliou = models.BooleanField(default=False)

    def __str__(self):
        return self.servico.nome

    def get_color(self):
        if self.status == 0:
            return 'green'
        elif self.status == 1:
            return 'blue'
        elif self.status == 2 or self.status == 3:
            return 'red'
        elif self.status == 4:
            return 'orange'
        else:
            return 'rgb(57,255,20)'

    def get_icon(self):
        if self.status == 0:
            return 'fa fa-clock-o'
        elif self.status == 1:
            return 'fa fa-hourglass-end'
        elif self.status == 2 or self.status == 3:
            return 'fa fa-exclamation-triangle'
        elif self.status == 4:
            return 'fa fa-credit-card'
        else:
            return 'fa fa-check-square'

    class Meta:
        verbose_name_plural = 'Solicitações'
        verbose_name = 'Solicitação'


class Orcamento(models.Model):

    prestador = models.ForeignKey(Prestador, on_delete=models.CASCADE)
    solicitacao = models.ForeignKey(Solicitacao, on_delete=models.CASCADE)
    descartar = models.BooleanField(default=False)
    descricao = models.TextField('Descrição')
    valor = models.DecimalField('Valor', decimal_places=2, max_digits=10)

    def __str__(self):
        return self.prestador.user.get_full_name() + ' - ' + str(self.valor)

    class Meta:
        verbose_name_plural = 'Orçamentos'
        verbose_name = 'Orçamento'

orcamentos/forms.py
from django.forms import ModelForm, Textarea
from .models import Solicitacao, Orcamento
from usuarios.models import Endereco
from django.utils.translation import gettext_lazy as _


class SolicitacaoForm(ModelForm):

    class Meta:
        model = Solicitacao
        fields = ['descricao', 'endereco']
        widgets = {
            'descricao': Textarea(attrs={'cols': 40, 'rows': 5, }),
        }
        labels = {
            'descricao': _('Procure ser o mais específico possível.'),

        }

    def __init__(self, user, *args, **kwargs):
        super(SolicitacaoForm, self).__init__(*args, **kwargs)
        self.fields['endereco'].queryset = Endereco.objects.filter(usuario=user)


class OrcamentoForm(ModelForm):

    class Meta:
        model = Orcamento
        fields = ['descricao', 'valor']

orcamentos/views.py
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from .models import Solicitacao, Orcamento
from catalogo.models import Servico
from usuarios.models import Cliente, Categoria, Prestador
from .forms import SolicitacaoForm, OrcamentoForm
from django.contrib import messages
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse
from usuarios.decorators import cliente_required, prestador_required
# Create your views here.


@method_decorator([login_required(login_url='usuarios:login'), cliente_required(login_url='usuarios:login')], name='dispatch')
class SolicitacaoView(CreateView):

    model = Solicitacao
    form_class = SolicitacaoForm
    template_name = 'orcamentos/nova_solicitacao.html'

    def form_valid(self, form):
        form.instance.cliente = Cliente.objects.get(user=self.request.user)
        form.instance.servico = Servico.objects.get(slug=self.kwargs['slug'])
        form.save()

        return redirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super(SolicitacaoView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(SolicitacaoView, self).get_context_data(**kwargs)
        context['servico'] = Servico.objects.get(slug=self.kwargs['slug'])

        return context

    def get_success_url(self):
        messages.success(self.request, 'Solicitado com sucesso!')
        return reverse('usuarios:solicitacoes_cliente')


@method_decorator([login_required(login_url='usuarios:login'), cliente_required(login_url='usuarios:login')], name='dispatch')
class SolicitacaoListView(ListView):
    template_name = 'orcamentos/minhas_solicitacoes.html'
    context_object_name = 'solicitacoes'

    def get_queryset(self):
        return Solicitacao.objects.filter(cliente_id=self.request.user.cliente.pk)


@method_decorator([login_required(login_url='usuarios:login'), prestador_required(login_url='usuarios:login')], name='dispatch')
class OrcamentoView(CreateView):

    model = Orcamento
    form_class = OrcamentoForm
    template_name = 'orcamentos/novo_orcamento.html'

    def form_valid(self, form):
        form.instance.prestador = Prestador.objects.get(user=self.request.user.prestador)
        form.instance.solicitacao = Solicitacao.objects.get(pk=self.kwargs['pk'])
        form.save()

        return redirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super(OrcamentoView, self).get_context_data(**kwargs)
        context['solicitacao'] = Solicitacao.objects.get(pk=self.kwargs['pk'])
        return context

    def get_success_url(self):
        messages.success(self.request, 'Orçamento enviado com sucesso!')
        return reverse('orcamentos:orcamentos-dados')


@method_decorator([login_required(login_url='usuarios:login'), prestador_required(login_url='usuarios:login')], name='dispatch')
class SolicitacoesAbertasListView(ListView):

    template_name = 'orcamentos/solicitacoes_prestador.html'
    context_object_name = 'solicitacoes'

    def get_queryset(self):

        prestador = self.request.user.prestador
        categorias = Categoria.objects.filter(prestador=prestador)

        return Solicitacao.objects.filter(servico__categoria__in=categorias, status=0)


@method_decorator([cliente_required(login_url='usuarios:login')], name='dispatch')
class OrcamentosListViewSolicitacoes(ListView):
    template_name = 'orcamentos/orcamentos_solicitacao.html'
    context_object_name = 'orcamentos'

    def get_context_data(self, **kwargs):
        context = super(OrcamentosListViewSolicitacoes, self).get_context_data(**kwargs)
        solicitacao = Solicitacao.objects.get(id=self.kwargs['pk'])

        context['servico'] = solicitacao.servico
        return context

    def get_queryset(self):
        return Orcamento.objects.filter(solicitacao_id=self.kwargs['pk'])


@cliente_required(login_url='usuarios:login')
def aceitarOrcamento(request, orcamentopk, solicitacaopk):

        orcamento = Orcamento.objects.get(pk=orcamentopk)
        solicitacao = Solicitacao.objects.get(pk=solicitacaopk)
        if solicitacao.cliente.user != request.user:
            messages.error(request, 'Você não tem permissão!')
            return redirect('index')
        else:
            if solicitacao.status != 0:
                messages.warning(request, 'Você já aceitou um orçamento para essa solicitação')
                return redirect('orcamentos:orcamentos_solicitacoes', solicitacaopk)
            else:
                solicitacao.status = 1
                solicitacao.orcamento_aceito = orcamento
                solicitacao.save()
                messages.success(request, 'Orçamento aceito com sucesso!')
                return redirect('orcamentos:orcamentos_solicitacoes', solicitacaopk)


@cliente_required(login_url='usuarios:login')
def cancelarSolicitacao(request, solicitacaopk):
    solicitacao = Solicitacao.objects.get(pk=solicitacaopk)
    if solicitacao.cliente.user != request.user:
        messages.error(request, 'Você não tem permissão!')
        return redirect('index')
    else:
        if solicitacao.status != 0:
            messages.error(request, 'Você já aceitou um orçamento, não há mais possibilidade de cancelamento')
            messages.warning(request, 'Em paralelo estamos trabalhando para melhorar as opções de cancelamento, agradecemos a compreensão')
            return redirect('usuarios:solicitacoes_cliente')
        else:
            solicitacao.status = 2
            solicitacao.save()
            messages.success(request, 'Solicitacção cancelada com sucesso!')
            return redirect('usuarios:solicitacoes_cliente')


@cliente_required(login_url='usuarios:login')
def descartarOrcamento(request, orcamentopk):
    orcamento = Orcamento.objects.get(pk=orcamentopk)
    if orcamento.solicitacao.cliente != request.user.cliente:
        messages.error(request, 'Você não tem permissão!')
        return redirect('index')
    else:
        if orcamento.descartar == 1:
            messages.warning(request, 'Orçamento já descartado')
            return redirect('orcamentos:orcamentos_solicitacoes', orcamento.solicitacao.pk)
        else:
            orcamento.descartar = 1
            orcamento.save()
            messages.success(request, 'Orçamento descartado com sucesso')
            return redirect('orcamentos:orcamentos_solicitacoes', orcamento.solicitacao.pk)


@cliente_required(login_url='usuarios:login')
def restaurarOrcamento(request, orcamentopk):
    orcamento = Orcamento.objects.get(pk=orcamentopk)
    if orcamento.solicitacao.cliente != request.user.cliente:
        messages.error(request, 'Você não tem permissão!')
        return redirect('index')
    else:
        if orcamento.descartar == 0:
            messages.warning(request, 'Orçamento já ativo')
            return redirect('orcamentos:orcamentos_solicitacoes', orcamento.solicitacao.pk)
        else:
            orcamento.descartar = 0
            orcamento.save()
            messages.success(request, 'Orçamento restaurado com sucesso')
            return redirect('orcamentos:orcamentos_solicitacoes', orcamento.solicitacao.pk)


@method_decorator([prestador_required(login_url='usuarios:login')], name='dispatch')
class OrcamentosPrestador(ListView):
    template_name = 'orcamentos/orcamentos_dados.html'
    context_object_name = 'orcamentos'

    def get_queryset(self):
        return Orcamento.objects.filter(prestador=self.request.user.prestador).order_by('solicitacao__servico__nome')


@prestador_required(login_url='usuarios:login')
def cancelarOrcamento(request, orcamentopk):
    orcamento = Orcamento.objects.get(pk=orcamentopk)
    try:
        solicitacao = Solicitacao.objects.get(orcamento_aceito=orcamento)
    except Solicitacao.DoesNotExist:
        solicitacao = None

    if orcamento.prestador != request.user.prestador:
        messages.error(request, 'Você não tem permissão!')
        return redirect('index')

    if solicitacao is None:
        messages.success(request, 'Orcamento cancelado com sucesso')
        orcamento.delete()
        return redirect('orcamentos:orcamentos-dados')

    if solicitacao.status != 0:
        messages.error(request, 'Orçamento já foi aceito, não há mais possibilidade de cancelamento')
        messages.warning(request, 'Em paralelo estamos trabalhando para melhorar as opções de cancelamento, agradecemos a compreensão')
        return redirect('orcamentos:orcamentos-dados')
    else:
        solicitacao.status = 3
        solicitacao.save()
        messages.success(request, 'orcamento cancelada com sucesso!')
        return redirect('orcamentos:orcamentos-dados')


@prestador_required(login_url='usuarios:login')
def confimarRealizacao(request, orcamentopk):
    orcamento = Orcamento.objects.get(pk=orcamentopk)
    try:
        solicitacao = Solicitacao.objects.get(orcamento_aceito=orcamento)
    except Solicitacao.DoesNotExist:
        solicitacao = None

    if orcamento.prestador != request.user.prestador:
        messages.error(request, 'Você não tem permissão!')
        return redirect('index')

    if solicitacao is None:
        messages.warning(request, 'Ocorreu um erro, tente novamente mais tarde')
        return redirect('orcamentos:orcamentos-dados')

    if solicitacao.status != 1:
        messages.error(request, 'Não é possível confirmar a realização do serviço')
        return redirect('orcamentos:orcamentos-dados')
    else:
        solicitacao.status = 4
        solicitacao.save()
        messages.success(request, 'solicitacao atulizada com sucesso!')
        return redirect('orcamentos:orcamentos-dados')

orcamentos/templates/orcamentos/orcamentos_dados.html
{% extends 'usuarios/minha_conta_cliente.html' %}
{% load widget_tweaks %}

{% block conta %}
    <div style="padding-bottom: 80px">
        <h3 class="pull-right mb-4"></h3>
    </div>
    <div>
        {% if not orcamentos %}
            <span id="notifications" class="">
                Você não possui nenhum Orçamento
            </span>
        {% else %}
            <h4 class="border-bottom border-gray pb-2 mb-0" style="margin-top: -70px !important;">Orçamentos para
            </h4>
            {% for orcamento in orcamentos %}
                <div class="my-3 p-3 bg-white rounded box-shadow" style="margin-left: -50px; ">
                    {% if orcamento.solicitacao.status == 5 or orcamento.solicitacao.status == 4 or orcamento.solicitacao.status == 2 %}
                        {% if  orcamento.solicitacao.prestador_avaliou %}
                            <badge class="badge badge-warning" style="float: right">já avaliado</badge>
                        {% endif %}
                    {% endif %}
                    {% if orcamento.solicitacao.orcamento_aceito == orcamento %}<span class="badge badge-success" style="float: right; margin-right: 5px">Aceito</span>{% endif %}

                    <div class="media pt-3">
                        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="" class="mr-2 rounded" width="32" height="32">
                        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">


                            {% if orcamento.solicitacao.orcamento_aceito == orcamento %}
                                <strong>Status:</strong> <strong style="color: {{ orcamento.solicitacao.get_color }}"> {{ orcamento.solicitacao.get_status_display }} </strong><i style="color: {{ orcamento.solicitacao.get_color }}" class="{{ orcamento.solicitacao.get_icon }}" aria-hidden="true"></i>
                            {% else %}
                                <strong>Status:</strong> <strong style="color: green"> Orçamento enviado </strong><i style="color: green" class="fa fa-clock-o" aria-hidden="true"></i>
                            {% endif %}
                        <br>
                            <strong class=" text-gray-dark">Cliente: </strong> <a href="{% url 'perfis:perfil_cliente' orcamento.solicitacao.cliente.pk %}"> {{ orcamento.solicitacao.cliente }}</a>
                            {% if orcamento.solicitacao.orcamento_aceito.prestador == user.prestador %}
                                {% if orcamento.solicitacao.status == 1 %}
                                    <br>
                                    <strong>Para ajustes de detalhes entre em contato com o cliente pelo
                                     Telefone:</strong> {{ orcamento.solicitacao.cliente.telefone }}
                                {% endif %}
                            {% endif %}
                            {% if orcamento.solicitacao.orcamento_aceito.prestador == user.prestador %}
                                {% if orcamento.solicitacao.status == 5 or orcamento.solicitacao.status == 4 or orcamento.solicitacao.status == 2 %}
                                    {% if not orcamento.solicitacao.prestador_avaliou %}
                                        <a href="{% url 'avaliacoes:avaliar_cliente' orcamento.pk %}"> <button class="btn btn-sm btn-outline-secondary" style="float: right">avaliar</button></a>
                                    {% endif %}
                                {% endif %}
                            {% endif %}

                            <strong class="d-block text-gray-dark">Descrição: </strong>{{ orcamento.solicitacao.descricao }}
                            <strong class="d-block text-gray-dark">Endereço: </strong>{{ orcamento.solicitacao.endereco }}

                        </p>

                        </div>
                            {% if orcamento.solicitacao.orcamento_aceito.prestador == user.prestador %}
                                {% if orcamento.solicitacao.status == 1 %}
                                    <a href="{% url 'orcamentos:confirma-realizacao' orcamento.pk %}"> <button class="btn btn-sm btn-success" style="float: right">Confirme aqui</button></a>
                                    <p style="float: right">Serviço foi já foi realizado?</p>
                                {% endif %}
                            {% endif %}
                        <a href="{% url 'orcamentos:cancelar-orcamento' orcamento.pk %}"><button type="button" class="btn btn-sm btn-outline-danger">Cancelar</button></a>
                        <a href=""><button type="button" class="btn btn-sm btn-outline-warning">Editar</button></a>
                    </div>
            {% endfor %}
        {% endif %}

    </div>


{% endblock %}

orcamentos/templates/orcamentos/orcamentos_solicitacao.html
{% extends 'usuarios/minha_conta_cliente.html' %}
{% load widget_tweaks %}

{% block conta %}
    <div style="padding-bottom: 80px">
        <h3 class="pull-right mb-4"></h3>
    </div>
    <div>
        {% if not orcamentos %}
            <span id="notifications" class="">
                Você não possui nenhum Orçamento
            </span>
        {% else %}
            <h4 class="border-bottom border-gray pb-2 mb-0" style="margin-top: -70px !important;">Orçamentos para {{ servico }}
            </h4>
            {% for orcamento in orcamentos %}
                {% if orcamento.descartar == False %}
                    <div class="my-3 p-3 bg-white rounded box-shadow" style="margin-left: -50px; ">
                        <div class="media pt-3">
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="" class="mr-2 rounded" width="32" height="32">
                            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                                <strong class=" text-gray-dark">Prestador: </strong> <a href="{% url 'perfis:prefil_prestador' orcamento.prestador.pk %}"> {{ orcamento.prestador }} </a>
                                <strong class="d-block text-gray-dark">Descrição: </strong>{{ orcamento.descricao }}
                            {% if orcamento.solicitacao.orcamento_aceito == orcamento %}<strong class="d-block text-gray-dark">Qualquer dúvida, você pode entrar em contato com o prestador pelo telefone:</strong> {{ orcamento.prestador.telefone }} {% endif %}
                            </p>
                            <span class="badge  badge-warning">R$ {{ orcamento.valor }}</span>
                            {% if orcamento.solicitacao.orcamento_aceito == orcamento %}<span class="badge badge-success">Aceito</span>{% endif %}
                        </div>
                        <a href="{% url 'orcamentos:aceitar-orcamento' orcamento.pk orcamento.solicitacao.pk %}"><button type="button" class="btn btn-sm btn-outline-success">Aceitar</button></a>
                        <a href="{% url 'orcamentos:descartar-orcamento' orcamento.pk %}"> <button type="button" class="btn btn-sm btn-outline-danger">Descartar</button></a>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
        <button class="btn btn-sm btn-outline-info" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="margin-left: -50px">
            Descartados
        </button>

    <div class="collapse" id="collapseExample" style="margin-left: -50px; padding: 15px 0 50px 0">
        <div class="card card-body">
            {% for orcamento in orcamentos %}
                {% if orcamento.descartar == True %}
                    <div class="media pt-3">
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="" class="mr-2 rounded" width="32" height="32">
                            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                            <strong class=" text-gray-dark">Prestador: </strong> <a href="{% url 'perfis:prefil_prestador' orcamento.prestador.pk %}"> {{ orcamento.prestador }} </a>
                            <strong class="d-block text-gray-dark">Descrição: </strong>{{ orcamento.descricao }}
                                <br>
                            <span class="badge  badge-warning">R$ {{ orcamento.valor }}</span>
                            <a href="{% url 'orcamentos:restaurar-orcamento' orcamento.pk %}"> <div class="btn btn-outline-secondary btn-sm"> Restaurar</div></a>
                    </div>
                {% endif %}
        {% endfor %}
        </div>
    </div>

{% endblock %}

orcamentos/templates/orcamentos/solicitacoes_prestador.html
{% extends 'usuarios/minha_conta_cliente.html' %}
{% load static %}
{% block conta %}


    {% if not solicitacoes %}
        <span id="notifications" class="">
        <br>
            Não existem solicitações nas categorias em que você está cadastrado <br><br>
        </span>
        Você pode escolher em que categorias deseja prestar serviços clicando <a href="{% url 'usuarios:categorias_prestador' %}"> aqui</a>

        {% else %}
    {% for solicitacao in solicitacoes %}
            <div class="my-3 p-3 bg-white rounded box-shadow" style="margin-left: -50px; ">
                <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                        <strong class="text-gray-dark">
                            {{ solicitacao.servico }}
                        </strong>
                </p>
                <div class="media pt-3">
                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                        <strong class="text-gray-dark">Serviço: </strong> {{ solicitacao.servico }}
                        <strong class=""><br>Endereco: </strong>{{ solicitacao.endereco }}
                        <strong class=""><br>Cliente: </strong><a href="{% url 'perfis:perfil_cliente' solicitacao.cliente.pk %}"> {{ solicitacao.cliente }}</a>
                        <strong class="d-block">Descrição:</strong>{{ solicitacao.descricao }}
                    </p>
                </div>
                <a href="{% url 'orcamentos:novo_orcamento' solicitacao.id %}"><button type="button" class="btn btn-sm btn-outline-primary">Dar um orçamento</button></a>
            </div>
    {% endfor %}
    {% endif %}

{% endblock %}